In [1]:
import pandas as pd
df = pd.read_csv("../datasets/nyc_weather.csv")
df['EST'] = pd.to_datetime(df['EST'])
df = df.set_index('EST')
new = df.select_dtypes(include='number').interpolate(method="time")
new

,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,CloudCover,WindDirDegrees
EST,,,,,,,,
2016-01-01,38,23,52,30.03,10,8.000000,5,281
2016-01-02,36,18,46,30.02,10,7.000000,3,275
2016-01-03,40,21,47,29.86,10,8.000000,1,277
2016-01-04,25,9,44,30.05,10,9.000000,3,345
2016-01-05,20,-3,41,30.57,10,5.000000,0,333
2016-01-06,33,4,35,30.50,10,4.000000,0,259
2016-01-07,39,11,33,30.28,10,2.000000,3,293
2016-01-08,39,29,64,30.20,10,4.000000,8,79
2016-01-09,44,38,77,30.16,9,8.000000,8,76
2016-01-10,50,46,71,29.59,4,7.333333,7,109
2016-01-11,33,8,37,29.92,10,6.666667,1,289
2016-01-12,35,15,53,29.85,10,6.000000,4,235
2016-01-13,26,4,42,29.94,10,10.000000,0,284
2016-01-14,30,12,47,29.95,10,5.000000,7,266
2016-01-15,43,31,62,29.82,9,5.000000,2,101
2016-01-16,47,37,70,29.52,8,7.000000,7,340
2016-01-17,36,23,66,29.78,8,6.000000,6,345
2016-01-18,25,6,53,29.83,9,12.000000,2,293
2016-01-19,22,3,42,30.03,10,11.000000,1,293
2016-01-20,32,15,49,30.13,10,6.000000,2,302
2016-01-21,31,11,45,30.15,10,6.000000,1,312
2016-01-22,26,6,41,30.21,9,11.000000,3,34
2016-01-23,26,21,78,29.77,1,16.000000,8,42
2016-01-24,28,11,53,29.92,8,6.000000,3,327
2016-01-25,34,18,54,30.25,10,3.000000,2,286
2016-01-26,43,29,56,30.03,10,7.000000,2,244
2016-01-27,41,22,45,30.03,10,7.000000,3,311
2016-01-28,37,20,51,29.90,10,5.000000,1,234
2016-01-29,36,21,50,29.58,10,8.000000,4,298
2016-01-30,34,16,46,30.01,10,7.000000,0,257
2016-01-31,46,28,52,29.90,10,5.000000,0,241

In [2]:
df2 = pd.DataFrame({
    'Rating': ['Excellent','Good','Poor']
})
new_df = df2.replace(['Excellent','Good','Poor'],[100,70,30])
new_df

C:\Users\ap504\AppData\Local\Temp\ipykernel_22064\3251091005.py:4: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  new_df = df2.replace(['Excellent','Good','Poor'],[100,70,30])

   Rating
0     100
1      70
2      30

In [3]:
new_df = df.groupby('Events')['Temperature'].mean()
new_df

Events
Fog-Snow    31.000000
Rain        45.500000
Snow        26.333333
Name: Temperature, dtype: float64