In [18]:
import  pandas as pd
df = pd.read_csv("../datasets/nyc_weather.csv")

Statistical Operations:

df['col'].max() / .min() / .mean() / .std()
df.describe() → Complete summary (count, mean, std, min, 25%, 50%, 75%, max)
25% / 50% / 75% = Quartiles, meaning that percentage of data lies below that value

In [19]:
df['Temperature'].max()

np.int64(50)

In [20]:
df['Temperature'].min()

np.int64(20)

In [21]:
df['Temperature'].mean()

np.float64(34.67741935483871)

In [22]:
df['Temperature'].std()

np.float64(7.639315400279416)

In [23]:
df.describe()

,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,CloudCover,WindDirDegrees
count,31.000000,31.000000,31.000000,31.000000,31.000000,28.000000,31.000000,31.000000
mean,34.677419,17.838710,51.677419,29.992903,9.193548,6.892857,3.129032,247.129032
std,7.639315,11.378626,11.634395,0.237237,1.939405,2.871821,2.629853,92.308086
min,20.000000,-3.000000,33.000000,29.520000,1.000000,2.000000,0.000000,34.000000
25%,29.000000,10.000000,44.500000,29.855000,9.000000,5.000000,1.000000,238.000000
50%,35.000000,18.000000,50.000000,30.010000,10.000000,6.500000,3.000000,281.000000
75%,39.500000,23.000000,55.000000,30.140000,10.000000,8.000000,4.500000,300.000000
max,50.000000,46.000000,78.000000,30.570000,10.000000,16.000000,8.000000,345.000000

Conditional Selection (Filtering):

df[df.Temperature >= 30] → Rows that satisfy the condition
df[df.Temperature == df['Temperature'].max()] → Row with the maximum value (DataFrame)
df['EST'][df.Temperature == df['Temperature'].max()] → Only a single column (Series)

In [24]:
df[df.Temperature >= 30]

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
0,1/1/2016,38,23,52,30.03,10,8.0,0,5,NaN,281
1,1/2/2016,36,18,46,30.02,10,7.0,0,3,NaN,275
2,1/3/2016,40,21,47,29.86,10,8.0,0,1,NaN,277
5,1/6/2016,33,4,35,30.50,10,4.0,0,0,NaN,259
6,1/7/2016,39,11,33,30.28,10,2.0,0,3,NaN,293
7,1/8/2016,39,29,64,30.20,10,4.0,0,8,NaN,79
8,1/9/2016,44,38,77,30.16,9,8.0,T,8,Rain,76
9,1/10/2016,50,46,71,29.59,4,NaN,1.8,7,Rain,109
10,1/11/2016,33,8,37,29.92,10,NaN,0,1,NaN,289
11,1/12/2016,35,15,53,29.85,10,6.0,T,4,NaN,235
13,1/14/2016,30,12,47,29.95,10,5.0,T,7,NaN,266
14,1/15/2016,43,31,62,29.82,9,5.0,T,2,NaN,101
15,1/16/2016,47,37,70,29.52,8,7.0,0.24,7,Rain,340
16,1/17/2016,36,23,66,29.78,8,6.0,0.05,6,Fog-Snow,345
19,1/20/2016,32,15,49,30.13,10,6.0,0,2,NaN,302
20,1/21/2016,31,11,45,30.15,10,6.0,0,1,NaN,312
24,1/25/2016,34,18,54,30.25,10,3.0,0,2,NaN,286
25,1/26/2016,43,29,56,30.03,10,7.0,0,2,NaN,244
26,1/27/2016,41,22,45,30.03,10,7.0,T,3,Rain,311
27,1/28/2016,37,20,51,29.90,10,5.0,0,1,NaN,234
28,1/29/2016,36,21,50,29.58,10,8.0,0,4,NaN,298
29,1/30/2016,34,16,46,30.01,10,7.0,0,0,NaN,257
30,1/31/2016,46,28,52,29.90,10,5.0,0,0,NaN,241

In [25]:
df[df.Temperature == df['Temperature'].max()]

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
9,1/10/2016,50,46,71,29.59,4,NaN,1.8,7,Rain,109

In [26]:
df['EST'][df.Temperature == df['Temperature'].max()]

9    1/10/2016
Name: EST, dtype: object

set_index() / reset_index()

df.set_index('col', inplace=True) → Set a column as the index
df.reset_index(inplace=True) → Reset back to default numeric index

In [27]:
df.index

RangeIndex(start=0, stop=31, step=1)

In [28]:
df.set_index('EST', inplace=True)

In [29]:
df.reset_index(inplace=True)

In [30]:
df.set_index('Humidity', inplace=True)

In [31]:
df.reset_index(inplace=True)